-- seed.sql
-- seed data for companies
-- Instructions: open in MySQL Workbench and run the entire file.
USE job_tracker;

INSERT INTO companies (greenhouse_token, name) VALUES
('mthree', 'mthree'),
('airbnb', 'Airbnb'),
('stripe', 'Stripe'),
('instacart', 'Instacart'),
('coinbase', 'Coinbase'),
('robinhood', 'Robinhood'),
('databricks', 'Databricks'),
('dropbox', 'Dropbox'),
('figma', 'Figma'),
('asana', 'Asana'),
('block', 'Block'),
('twilio', 'Twilio'),
('mongodb', 'MongoDB'),
('elastic', 'Elastic'),
('gitlab', 'GitLab'),
('reddit', 'Reddit'),
('pinterest', 'Pinterest'),
('lyft', 'Lyft'),
('affirm', 'Affirm'),
('chime', 'Chime'),
('brex', 'Brex'),
('gusto', 'Gusto'),
('hubspot', 'HubSpot'),
('okta', 'Okta'),
('duolingo', 'Duolingo'),
('coursera', 'Coursera'),
('udemy', 'Udemy'),
('roblox', 'Roblox'),
('epicgames', 'Epic Games'),
('riotgames', 'Riot Games'),
('disney', 'Disney'),
('datadog', 'Datadog'),
('newrelic', 'New Relic'),
('cloudflare', 'Cloudflare'),
('fastly', 'Fastly'),
('vercel', 'Vercel'),
('netlify', 'Netlify'),
('circleci', 'CircleCI'),
('scaleai', 'Scale AI'),
('anthropic', 'Anthropic'),
('deepmind', 'DeepMind'),
('airtable', 'Airtable'),
('intercom', 'Intercom'),
('mixpanel', 'Mixpanel'),
('amplitude', 'Amplitude'),
('klaviyo', 'Klaviyo'),
('toast', 'Toast');